# Generated by Django 3.0.3 on 2022-08-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prdoducto',
            new_name='Producto',
        ),
    ]
